### ISSUE TITLE
Binary in Any type writing failed

### ISSUE THREAD

**Issue by xuzhg** [Microsoft/OpenAPI.NET#386] opened 2019-02-27 22:25 UTC
If i have a OpenApiBinary object, it's not supported now in the writing the binary value.

The problem is at https://github.com/Microsoft/OpenAPI.NET/blob/master/src/Microsoft.OpenApi/Writers/OpenApiWriterAnyExtensions.cs#L173

It directly uses the value (its type is byte[]), and the underlying writer can't write the `byte[]` type.

**Comment by PerthCharern** [comment] 2019-03-13 23:25
Related issue: #379. 

This still hasn't been completely fixed I think. Reposting my comment from the PR since it already got merged: https://github.com/Microsoft/OpenAPI.NET/pull/387#discussion_r265248942

> My take would be:
> 
> Store OpenApiBinary as byte[]. The reader converts the string into byte array assuming it knows each character is a byte. I think in C#, this can be done by Encoding.ASCII.GetBytes(string);. The writer does the reverse: Encoding.ASCII.GetString(bytes);
> 
> We should also store OpenApiByte as byte[]. The reader converts the string into byte array using Convert.FromBase64String, and the writer converts the byte array into base64 string using Convert.ToBase64String.
> 
> This way we keep our principle of storing the underlying meaningful type that we does with Date/DateTime, and we allow the reader/writer to handle the (de-)serialization properly.

**Comment by darrelmiller** [comment] 2019-03-14 01:23
@PerthCharern   I'm ok with storing OpenApiBinary as a byte array, but shouldn't we do Encoding.UTF8.GetBytes(string) considering JSON is UTF-8 and probably 99.99% of yaml files are also UTF-8.  I agree with your solution to OpenApiByte.

**Comment by PerthCharern** [comment] 2019-03-14 01:56
Agree with you. The UTF-8 encoding makes more sense.

All that said, this Binary type seems pretty useless since in the doc it's just serialized as a normal string, representing itself - the only benefit our model is offering is converting and storing it into byte[]. 

From the spec standpoint, is there really any difference when someone specifies a string as string without format vs string with Binary format? One thing I can think of is it is EXPLICITLY saying that this is indeed a string that should be taken as is, not a string that represents bytes (like the Byte format).

**Comment by darrelmiller** [comment] 2019-03-14 02:31
@PerthCharern From the spec standpoint, the format means nothing.  It is purely a hint to tooling on how to interpret the data.  IT doesn't affect the wire format, or how the HTTP request is made.  Tooling can choose to validate data based on the format, but there is no requirement in the spec for this.
This is a very loose solution that was designed to avoid having to go down the rathole of defining an exhaustive type system.  Is not a great solution, but it is very flexible and allows API designers to create their own formats that need to be agreed upon between client and server.

**Comment by PerthCharern** [comment] 2019-03-14 17:56
@darrelmiller That makes sense. My original thought was more like - to those tools that read the spec, what's the difference between "string : binary" and just "string". I guess I answered my own question though since our tool recognizes the different nature of the underlying data and is now storing them differently too :)

**Comment by darrelmiller** [comment] 2019-04-10 02:14
Fixed in #391

**Closed by darrelmiller** 2019-04-10 02:14 UTC
