### ISSUE TITLE
Example value is switching type

### ISSUE THREAD

**Issue by richardkaspar** [microsoft/OpenAPI.NET#1224] opened 2023-04-19 12:28 UTC
**Describe the bug**
Reading an OpenAPI document containing an example value of type integer will switch the type to string. 
Microsoft.OpenApi.Readers 1.6.3

**To Reproduce**
Use the following code with Microsoft.OpenApi.Readers 1.6.3.
Open the two files in a compare tool.
Code:
```
            using var stream = new FileStream(readFile, FileMode.Open, FileAccess.Read);

            var doc =
                new OpenApiStreamReader(
                        new OpenApiReaderSettings
                        {
                            ReferenceResolution = ReferenceResolutionSetting.DoNotResolveReferences
                        })
                   .Read(stream, out _);

            var sb = new StringBuilder();

            var writer = new OpenApiYamlWriter(new StringWriter(sb, new CultureInfo("en_us")));

            doc.SerializeAsV3(writer);

            File.WriteAllText(writeFile, sb.ToString());
```

readFile:

```
openapi: 3.0.1
info:
  title: example
  description: Sample description
  version: 0.1.9
paths:
  /foo:
    get:
      responses:
        '200':
          description: bla bla
components:
  examples:
    FooInt:
      value: 666

```

writeFile:

```
openapi: 3.0.1
info:
  title: example
  description: Sample description
  version: 0.1.9
paths:
  /foo:
    get:
      responses:
        '200':
          description: bla bla
components:
  examples:
    FooInt:
      value: '666'
```

**Expected behavior**
The content of writeFile and readFile should be equal.

**Screenshots/Code Snippets**
![grafik](https://user-images.githubusercontent.com/98944439/233073162-86382b07-2f20-486e-853e-30912cad965f.png)

**Additional context**

**Comment by darrelmiller** [comment] 2023-05-12 20:33
Confirmed this is a bug.  This will be resolved with v2 because we are no longer going to try parsing examples into a strongly typed structure.

**Comment by MaggieKimani1** [comment] 2024-02-12 12:24
Closing this as completed.

**Closed by MaggieKimani1** 2024-02-12 12:24 UTC
Labels: type:bug
