### ISSUE TITLE
ValidateOneOfDiscriminator errors

### ISSUE THREAD

**Issue by michivogler** [microsoft/OpenAPI.NET#383] opened 2019-02-18 10:15 UTC
I'm currently trying to generate an OpenAPI documentation using this library. When I try to add a discriminator in combination with `oneOf` I get a ton of errors after validation for the `ValidateOneOfDiscriminator` rule and I can't figure out what exactly is wrong.

Error message examples:
```
Composite Schema EmailAddress must contain property specified in the discriminator Type. [#/paths/~1Addresses/get/responses/200/content/application~1json/schema/items/oneOf]

Composite schema EmailAddress must contain property specified in the discriminator Type in the required field list. [#/paths/~1Addresses/get/responses/200/content/application~1json/schema/items/oneOf]
```

When I serialize the `OpenApiDocument` and copy it to https://editor.swagger.io/ everything seems to be valid. Even if I use the `OpenApiStreamReader` and validate it again there are no errors and after serializing it again there's no diff between the two documents.

Any idea what the problem might be?

Here's a short version of my openapi.yaml
```
openapi: 3.0.1
info:
  title: My API
  version: v1
paths:
  /Addresses:
    get:
      tags:
        - Addresses
      operationId: AddressesGetAll
      parameters:
        - name: pageIndex
          in: query
          schema:
            type: string
        - name: pageSize
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/EmailAddress'
                    - $ref: '#/components/schemas/PostalAddress'
                    - $ref: '#/components/schemas/WebAddress'
                  discriminator:
                    propertyName: Type
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
components:
  schemas:
    WebAddress:
      required:
        - Type
        - Uri
      type: object
      properties:
        VerifiedDate:
          type: string
          format: date-time
          readOnly: true
        Version:
          type: number
          format: int32
          readOnly: true
        CreatedTime:
          type: string
          format: date-time
          readOnly: true
        UpdatedTime:
          type: string
          format: date-time
          readOnly: true
        IsVerified:
          type: boolean
          readOnly: true
        Type:
          type: string
          readOnly: true
        VerificationCode:
          type: string
        Guid:
          type: string
          format: uuid
          readOnly: true
        IsAdvertisingAllowed:
          type: boolean
        Uri:
          type: string
        DisplayName:
          type: string
          readOnly: true
    EmailAddress:
      required:
        - Address
        - Type
      type: object
      properties:
        Address:
          type: string
        VerifiedDate:
          type: string
          format: date-time
          readOnly: true
        Version:
          type: number
          format: int32
          readOnly: true
        CreatedTime:
          type: string
          format: date-time
          readOnly: true
        UpdatedTime:
          type: string
          format: date-time
          readOnly: true
        IsVerified:
          type: boolean
          readOnly: true
        Domain:
          type: string
          readOnly: true
        Type:
          type: string
          readOnly: true
        VerificationCode:
          type: string
        Guid:
          type: string
          format: uuid
          readOnly: true
        IsAdvertisingAllowed:
          type: boolean
        DisplayName:
          type: string
          readOnly: true
    PostalAddress:
      required:
        - Country
        - City
        - Type
      type: object
      properties:
        Longitude:
          type: string
        Region:
          type: string
        Zipcode:
          type: string
        City:
          type: string
        VerifiedDate:
          type: string
          format: date-time
          readOnly: true
        Version:
          type: number
          format: int32
          readOnly: true
        CreatedTime:
          type: string
          format: date-time
          readOnly: true
        State:
          type: string
        UpdatedTime:
          type: string
          format: date-time
          readOnly: true
        StreetName:
          type: string
        IsVerified:
          type: boolean
          readOnly: true
        Type:
          type: string
          readOnly: true
        VerificationCode:
          type: string
        Guid:
          type: string
          format: uuid
          readOnly: true
        Latitude:
          type: string
        IsAdvertisingAllowed:
          type: boolean
        DisplayName:
          type: string
          readOnly: true
        StreetNumber:
          type: string
        PoBox:
          type: string
```

**Comment by michivogler** [comment] 2019-02-18 12:16
Here's a test to reproduce the error:
```cs
[Fact]
public void ValidateOneOfDiscriminatorTest()
{
	var openApiDocument = new OpenApiDocument
	{
		Info = new OpenApiInfo {Title = "My API", Version = "v1"},
		Components = new OpenApiComponents(),
		Paths = new OpenApiPaths
		{
			["/people"] = new OpenApiPathItem
			{
				Operations = new Dictionary<OperationType, OpenApiOperation>
				{
					[OperationType.Get] = new OpenApiOperation
					{
						Description = "Returns all people",
						Responses = new OpenApiResponses
						{
							["200"] = new OpenApiResponse
							{
								Description = "OK",
								Content = new Dictionary<string, OpenApiMediaType>
								{
									["application/json"] = new OpenApiMediaType
									{
										Schema = new OpenApiSchema
										{
											Type = "array",
											Items = new OpenApiSchema
											{
												Discriminator = new OpenApiDiscriminator
												{
													PropertyName = "Type"
												},
												OneOf = new List<OpenApiSchema>
												{
													new OpenApiSchema
													{
														Reference = new OpenApiReference
														{
															Type = ReferenceType.Schema,
															Id = "Person"
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	};

	openApiDocument.Components.Schemas.Add("Person", new OpenApiSchema
	{
		Type = "object",
		Required = new HashSet<string> {"Type", "Name"},
		Properties = new Dictionary<string, OpenApiSchema>
		{
			{"Type", new OpenApiSchema {Type = "string"}},
			{ "Name", new OpenApiSchema {Type = "string"}}
		}
	});

	var openApiErrors = openApiDocument.Validate(ValidationRuleSet.GetDefaultRuleSet());
	Assert.Empty(openApiErrors);
}
```

**Comment by PerthCharern** [comment] 2019-04-28 18:36
#384 should partially fix this, but I think there's still the same bug with #402 that remains. We are not looking into the properties of the children schema to check the `required` properties.

**Comment by baywet** [comment] 2022-06-28 12:28
closing as duplicate of #402 as we have more people engaged on 402

**Closed by baywet** 2022-06-28 12:28 UTC
Labels: bug
