### ISSUE TITLE
Missing "version" key.

### ISSUE THREAD

**Issue by nduijvelshoff** [Microsoft/OpenAPI.NET#369] opened 2018-12-13 01:27 UTC
Hi there,

I'm possibly doing something very wrong, but why don't I get the "openapi" key specified?

My current output:
![image](https://user-images.githubusercontent.com/3780207/49909285-778f1400-fe7e-11e8-9b1a-dd36c91b0212.png)

While it should be like this:
![image](https://user-images.githubusercontent.com/3780207/49909309-8ece0180-fe7e-11e8-85cc-6b7f5a8f36e5.png)

My code is:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.OpenApi.Expressions;
using Microsoft.OpenApi.Models;
using Microsoft.OpenApi.Writers;

namespace hoppa.Service.Controllers
{
    [Route("api/v1.0/[controller]")]
    public class OpenApiController : ControllerBase
    {
        public IActionResult Get()
        {
            var document = new OpenApiDocument
            {
                Info = new OpenApiInfo
                {
                    Version = "1.0.0",
                    Title = "hoppa",
                    License = new OpenApiLicense
                    {
                        Name = "MIT"
                    },
                    Contact = new OpenApiContact
                    {
                        Name = "Nick Duijvelshoff",
                        Email = "online@hoppa.app"
                    }
                },
                Servers = new List<OpenApiServer>
                {
                    new OpenApiServer { Url = "https://service.dev.hoppa.app/api/v1.0/" }
                },
                Tags = new List<OpenApiTag>
                {
                    new OpenApiTag {
                        Name = "People",
                        Description = "People operations"
                    }
                },
                Paths = new OpenApiPaths
                {
                    ["/people"] = new OpenApiPathItem
                    {
                        Operations = new Dictionary<OperationType, OpenApiOperation>
                        {
                            [OperationType.Get] = new OpenApiOperation
                            {
                                Tags = new List<OpenApiTag>{
                                    new OpenApiTag {
                                        Name = "People"
                                    }
                                },
                                Description = "Returns all people from the system that the user has access to.",
                                Responses = new OpenApiResponses
                                {
                                    ["200"] = new OpenApiResponse
                                    {
                                        Description = "OK"
                                    }
                                }
                            }
                        }
                    }
                }
            };

            return Ok(document);
        }
    }
}
```

**Comment by PerthCharern** [comment] 2018-12-13 01:41
Hi @nduijvelshoff.

The standard JSON serialization of the C# object won't yield the correct OpenAPI document. This is by design for many reasons, e.g. to allow serialization in both V2 and V3, to allow storing extensions which don't fit well with the normal C# object, etc.

You will need to serialize the document using the serializer in our library:

```
document.Serialize(OpenApiSpecVersion.OpenApi3_0, OpenApiFormat.Json);
```

Let me know if this works for you.

**Comment by nduijvelshoff** [comment] 2018-12-13 01:49
@PerthCharern thanks for the amazingly quick response!

I tryied your suggestion before, but then I'm getting the following error:

![image](https://user-images.githubusercontent.com/3780207/49910069-aa86d700-fe81-11e8-9c47-de630be908bf.png)

Am I missing a namespace?

**Comment by nduijvelshoff** [comment] 2018-12-13 01:57
In addition to my previous comment, before I selected `SerializeAsV3` I got the following options since `Serialize` doesn't exist:
![image](https://user-images.githubusercontent.com/3780207/49910388-d8b8e680-fe82-11e8-802a-f3c6e2c938fb.png)

**Comment by nduijvelshoff** [comment] 2018-12-13 02:17
So I figured that seem to be missing the `Microsoft.OpenApi` namespace for the `OpenApiSpecVersion` and `OpenApiFormat`. So now its:
![image](https://user-images.githubusercontent.com/3780207/49911076-5a117880-fe85-11e8-92f1-e7f539aa2f48.png)
I still get the error that `OpenApiDocument` doesn't contain a definition for: `Serializer`

**Comment by PerthCharern** [comment] 2018-12-13 02:30
The Serialize extension is in this namespace:

Microsoft.OpenApi.Extensions

https://github.com/Microsoft/OpenAPI.NET/blob/master/src/Microsoft.OpenApi/Extensions/OpenApiSerializableExtensions.cs

Does that work?

**Comment by nduijvelshoff** [comment] 2018-12-13 02:33
That's it! Thanks @PerthCharern !

**Comment by PerthCharern** [comment] 2018-12-13 02:34
Glad that works! I'll close this, but feel free to open any new issues if you run into any other problems.

**Closed by PerthCharern** 2018-12-13 02:34 UTC
